/stone_station_detector:
  ros__parameters:
    color: true # red: true
                # blue: false

  # Camera config params.
    camera_name: "KS2A543" 
    camera_type: 0 #(/usb: 0 / usb_01: 1 / usb_02: 2)
    camera_param_path: "src/global_user/config/camera.yaml"

  # Network model path.
    network_path: "src/engineer_exchange_stone/model/yolox_123.onnx"
  
  # # Data saving.
  #   save_data: false
  #   save_path: "src/data/infer2_5.txt"
  
  # Debug params.
    debug: true
    using_imu: false
    show_img: true
    show_fps: true
    print_letency: false
    print_target_info: false
    detect_red: true
    show_aim_cross: false
    show_target: true
    show_transform: false

