/station_detector:
  ros__parameters:
  # 自瞄检测节点参数配置
    color: true # red: true
                # blue: false
    # no_crop_ratio: 2e-3
    # full_crop_ratio: 1e-4

    #待改
    camera_name: "KS2A543" 
    camera_param_path: "src/global_user/config/camera.yaml"
    network_path: "src/stone_station_detector/model/opt-0527-002.xml"

    #debug
    debug_without_com: true
    # using_roi: true
    # show_aim_cross: false
    show_img: true
    show_fps: true
    # print_letency: false
    print_target_info: true
    detect_red: true

